### ISSUE TITLE
command 'extension.sendPythonToMaya' not found

### ISSUE THREAD

**Issue by axxxj** [NCCA/mayaport#1]
A new install of this extension in VSCode 1.4.0, after restarting and trying to send some python code to Maya I get "command 'extension.sendPythonToMaya' not found"?

**Comment by jmacey** [comment]
Have you run the initial mayaPort command? This is required to open up the sockets etc.

Open up the  Command Palette and type  mayaPort and press enter to start it up.

On 25 Aug 2016, at 11:32, axxxj <notifications@github.com<mailto:notifications@github.com>> wrote:

A new install of this extension in VSCode 1.4.0, after restarting and trying to send some python code to Maya I get "command 'extension.sendPythonToMaya' not found"?

BU is a Disability Two Ticks Employer and has signed up to the Mindful Employer charter. Information about the accessibility of University buildings can be found on the BU DisabledGo webpages This email is intended only for the person to whom it is addressed and may contain confidential information. If you have received this email in error, please notify the sender and delete this email, which must not be copied, distributed or disclosed to any other person. Any views or opinions presented are solely those of the author and do not necessarily represent those of Bournemouth University or its subsidiary companies. Nor can any contract be formed on behalf of the University or its subsidiary companies via email.

**Comment by axxxj** [comment]
I had already done that, I have checked and tried running it again but the ports are already open.
Still get the same error in VS Code!
Don't worry it isn't urgent, I just thought it would be helpful to open up an issue about it.
Thanks.

**Comment by jmacey** [comment]
Are there any other messages in the output console?
On 25 Aug 2016, at 11:46, axxxj <notifications@github.com<mailto:notifications@github.com>> wrote:

Don't worry it isn't urgent, I just thought it would be helpful to open up an issue about it.

BU is a Disability Two Ticks Employer and has signed up to the Mindful Employer charter. Information about the accessibility of University buildings can be found on the BU DisabledGo webpages This email is intended only for the person to whom it is addressed and may contain confidential information. If you have received this email in error, please notify the sender and delete this email, which must not be copied, distributed or disclosed to any other person. Any views or opinions presented are solely those of the author and do not necessarily represent those of Bournemouth University or its subsidiary companies. Nor can any contract be formed on behalf of the University or its subsidiary companies via email.

**Comment by axxxj** [comment]
No nothing, sorry! It might just be a strange installation issue or something... I'll try restarting my machine soon, that is always a good place to start...

**Comment by oglops** [comment]
I have this problem now, latest extension, vscode 1.38, cent os 7.6, maya 2019.2, port opened already, the other extension `mayaCode` works fine.
